package com.seismotech.hashish.impl.murmur3;

/* Autogenerated class.
 * See ideas/murmur/murmur3/generate-data.cpp
 */
class MurmurTestData {
  static final int[] SEEDS = {0x0,0x5e15aa0,0xf5e15aa0,};
  static final String VERSE = "Will it get some wind for the sailboat";
  static final long[][][] EXPECTED = {
    {
      {0x0L, 0x0L, 0x0L},
      {0x23936c7cL, 0x3afa3146L, 0x52b3c08f5c974acaL},
      {0xec3754ccL, 0x8259183L, 0x813bcf82d8c1dd14L},
    },
    {
      {0xc2992670L, 0x858e1199L, 0xb3c645d972ace3bbL},
      {0x55effc04L, 0x9afd9556L, 0xf25639752e6658b3L},
      {0xad65532fL, 0xcb433b5dL, 0xd9e031754bd5478fL},
    },
    {
      {0x72dd370dL, 0x3b796bdcL, 0x2b8b01bb3b41aae2L},
      {0xc624985dL, 0xf51d40dL, 0xa932f6a46acd3ca8L},
      {0xec8a8177L, 0x3f94a9f9L, 0x56ee198bd7af83afL},
    },
    {
      {0x17373ef2L, 0xf25e68fdL, 0xd85bbc98a3503d02L},
      {0xfb5a549dL, 0x5df5c4aL, 0xdcc84276879427afL},
      {0x3c7e443dL, 0xa5e11a29L, 0xc2101f135a373849L},
    },
    {
      {0x5c1c495fL, 0x5decc9dL, 0xc70cfc537fe5e401L},
      {0xf80a8201L, 0x16f45998L, 0x705b0e186e1b41adL},
      {0xe3c16b9aL, 0xe37e8bfeL, 0xfbf92d8678f0dc1fL},
    },
    {
      {0x194a0b7dL, 0xb1bee810de431d32L, 0x818b93e3eead3ad4L},
      {0x43543b5aL, 0xebf3cca49ff6faccL, 0x4a89131ed8e5309fL},
      {0x7b8c18b5L, 0x148d4f338e16ec06L, 0x3f899c8214b8d33dL},
    },
    {
      {0x59919432L, 0x9195bf3d5709fbbdL, 0x7b93c5f53a0cbed9L},
      {0x5e323bf5L, 0xb2c0796b448413e1L, 0x1412b24ad07f1c68L},
      {0xfb872b3bL, 0x188f56da1faee2caL, 0x87bd958846432380L},
    },
    {
      {0x36dd13f5L, 0x3defb07083faeb5aL, 0x4bcb377d691db70aL},
      {0xb8533557L, 0x796bac54f6e3b89cL, 0x8c1af5b7a12730dcL},
      {0xebaa8bdfL, 0x4bf770139c0f90L, 0x841ed0ea7f481c16L},
    },
    {
      {0xdf1bb08bL, 0x91ff3dddf4e0b106L, 0x48056ac3f4dcc2bbL},
      {0xb7362157L, 0xa778d4beadb2d5c8L, 0x222d96306921483dL},
      {0x91cf24a1L, 0xb24b071b3dff8b3aL, 0x968a88eed9551fe6L},
    },
    {
      {0x1d948e62L, 0x3579626c1d6a279fL, 0xc618f8db46f34f7aL},
      {0x4a0caf9eL, 0x145b74e4afce53efL, 0x80c152ba5f03fa35L},
      {0xa5cdd58L, 0x961cbe72374a63f4L, 0xd40b6b0046ba0322L},
    },
    {
      {0x470dbd2dL, 0x94d7c0e09450dabeL, 0x14c3c165b46dbe7dL},
      {0x10dc6b4eL, 0xbe9b7cd3cfa10e2fL, 0x56eb1c5b1570d07fL},
      {0x6c1566b0L, 0xe546b2217e4ace95L, 0xe4cc47c84be770c0L},
    },
    {
      {0x6d7dbf17L, 0x2271f1c7a927b1e3L, 0x7f8643d81c8ac4a8L},
      {0x4dc96343L, 0xea9d5610f080ba83L, 0x8e713eaf66304573L},
      {0xe4c89aacL, 0xb5cd2b63d5d10114L, 0xbcf3a673436a6fc7L},
    },
    {
      {0xb8920b3bL, 0xd6bfac5ae172c257L, 0xeda4484735a09a8aL},
      {0x45b894c9L, 0x552de71aad8ec105L, 0x2583a177ad544716L},
      {0x65263043L, 0x88551218ecd06861L, 0x2f61c5d963e571b4L},
    },
    {
      {0x4eaa5417L, 0x31b38215aa252911L, 0x63c061042cfaac2eL},
      {0xff4842a4L, 0x81caf596610de8b4L, 0x6009d36f30dae127L},
      {0x33caa0b8L, 0xf8dc4656377e4decL, 0xa157470c94442ef6L},
    },
    {
      {0xd9ebc225L, 0x7856c0f03f305748L, 0x9552a3e6d40af8f5L},
      {0xee41a5bcL, 0x7b7fb5f25e7959cdL, 0xb81a9004f1d5ed1bL},
      {0x36571039L, 0xfd245025022ca561L, 0x44ce339d0002d23aL},
    },
    {
      {0x62d8e3b9L, 0xb50606381bdc08f8L, 0x9a5f9233ef71d716L},
      {0x803e4464L, 0x6d837d11bfccd4acL, 0x5f478f5b33394f6cL},
      {0xb2b7e905L, 0xe8a48f19a7fd3691L, 0x7e67d6965ecc62d1L},
    },
    {
      {0x4a4f8872L, 0x475f673a76efaf7cL, 0x2408ef2a9f3408fL},
      {0xc339947bL, 0x128de460d4467de3L, 0x202538879a3e68b9L},
      {0x54c0b94cL, 0x8c8338ddd6db6d04L, 0x3310ac5cd2572300L},
    },
    {
      {0xa7e59a04L, 0x366e841d6fe880ebL, 0xee80fcc2c3be7e55L},
      {0x201c9e31L, 0x4a47a220b28aa785L, 0x49f369e2dd6b5d1bL},
      {0x4d3f954cL, 0xc26408fa5565abaeL, 0x98e70917471c093cL},
    },
    {
      {0xdb9f4356L, 0x8068f85e1d2c328cL, 0x8ccc01ed199d0496L},
      {0xb6c7f301L, 0x648059ecc3031abaL, 0xd75f566edbca5a3aL},
      {0x19567fdbL, 0xe9668a424d954758L, 0xd92d19a210a440ceL},
    },
    {
      {0x977016faL, 0x4dfd9a145a44e590L, 0xde020121cdf7f276L},
      {0x1edcdfbcL, 0x88972600d93021c5L, 0xbb15c8c8288e03f8L},
      {0xab799173L, 0x2ef7aa8ec4ae8970L, 0x5d79730341ff5dc1L},
    },
    {
      {0xe1c51a2cL, 0x823c982fbf27a675L, 0xb510d6a1b62b0483L},
      {0xd64310e5L, 0x973190e3cabee3a5L, 0x9de1039eaaeda947L},
      {0xc99f4e37L, 0x42a6eec8f8e22e4bL, 0x9630434a6a86550dL},
    },
    {
      {0xcef7b0d4L, 0xf7ecb8ca5b1b635bL, 0xfc2fa52d8b0f89f1L},
      {0xb7c6bae5L, 0xa4fcd1af84955bffL, 0xb58249079100f78L},
      {0x7a1078a0L, 0x75273d17d0910fc5L, 0x332b132bffe5d03cL},
    },
    {
      {0x877ee15aL, 0x56ef0e64ffbc9461L, 0xc4fee50e571204bbL},
      {0x834820a1L, 0xb37596350767b947L, 0x24c0f7b92feb73f4L},
      {0x9bb45c36L, 0x58a7644e999912b1L, 0x342e05c0b2a3b717L},
    },
    {
      {0x6ee9dbd7L, 0x8081b6793a9df6f3L, 0xae2dba225aac72dbL},
      {0x813b071dL, 0xe5d17a436ccb1a9aL, 0x90b80bea710a76fdL},
      {0x11599b49L, 0xdb4eb14b8f71824cL, 0xb0317730349a602cL},
    },
    {
      {0x9b4f0b45L, 0x54c5268f66bb8091L, 0x18d528e346b350ecL},
      {0xa22c7946L, 0xc91505d39f5ae07cL, 0x7b0672a1c82758caL},
      {0x2d70c9eL, 0xcec5423358a90623L, 0xa603fb3b05ae06d7L},
    },
    {
      {0x6023d471L, 0x58ade31d1c969e2aL, 0x1df34e6b5aeb221L},
      {0x57357733L, 0x544beb86db64500dL, 0x2252e366777cabccL},
      {0x3ba318f8L, 0x9f9ed76cc3657264L, 0x8866eb749d75baaeL},
    },
    {
      {0x258c508cL, 0xd94c1fcfeb530c11L, 0x29644cc35f1075f0L},
      {0x1a32eea8L, 0x71883a6a74426e77L, 0x40cb3b96b38bf6b1L},
      {0x7b19569cL, 0x50841481ef10a3afL, 0xadf0fb75299610bL},
    },
    {
      {0x199250c0L, 0xa874cfb1cbced0f2L, 0xc4efff29bf87c104L},
      {0x7b5bd753L, 0xd73a297d77beba48L, 0xb38137ff7c3e67c0L},
      {0x259d75efL, 0xee2541c6dfdcd246L, 0x1eb465ec4156dc2aL},
    },
    {
      {0x516c90abL, 0x9a5e9c89649642d1L, 0xf0f2106f14a5c150L},
      {0x38093374L, 0x208cd7660aa05eebL, 0x6d0de47961601a93L},
      {0x52a23ec6L, 0x25d1ddf6aff2dc73L, 0xcdd337fdf8dc1f5bL},
    },
    {
      {0x9be1b8f0L, 0x76463cebfd2cd8f2L, 0x3631af8b750c34b1L},
      {0x7a8b085aL, 0x3a1e514f59478649L, 0x7920214ca9b4f717L},
      {0x55e01d82L, 0xebf2a6c3c47a0c3dL, 0x843aa3e259967b5eL},
    },
    {
      {0x165cd35cL, 0x8db1ae7aeac726aaL, 0x7ed4935594a2a69aL},
      {0x702393f3L, 0x620ba8209d9438adL, 0x322c182a5c27d493L},
      {0x244a4e9bL, 0xdb5b4ff317dc3f1cL, 0xd46679b9c95cd268L},
    },
    {
      {0x3ed9589fL, 0xe6d9750b24e235b6L, 0x66d9916c3d032747L},
      {0x8a2fa369L, 0xea61ec1d2ae2603aL, 0x67b7f2951db3ece8L},
      {0x76deabefL, 0xb59d4521619f4f21L, 0xa26d39645edd2b13L},
    },
    {
      {0x2f93cb39L, 0xf1e71171f7523ffdL, 0x3df043bb5dd5b2ccL},
      {0xb69e1d92L, 0x4c7758a4e8e658e1L, 0xfe622d93b19b7fa5L},
      {0x4f1d20b0L, 0x13338bbb4532ecb9L, 0xe500731b97c641b8L},
    },
    {
      {0xa49de380L, 0x2bb34670ca29fc84L, 0xd2ab72536c6afbd9L},
      {0x2cf3e005L, 0x9e8f67baac70b257L, 0x705c94a89d8c17f5L},
      {0x5ccde1b9L, 0x6b4b24e34bb6ba4dL, 0xa56f5f4651ad652bL},
    },
    {
      {0x9b54142dL, 0xd2c789247ed88a01L, 0xc9ec5b9f8e0d730aL},
      {0xd4f9ec30L, 0xe77ff0eb378391d5L, 0x4f768d9a2c2c7cb1L},
      {0x7ed5e498L, 0x967cfc624778d0cL, 0x4e3db05c6ec90163L},
    },
    {
      {0xe95f38c3L, 0xd39a44998eedaf4aL, 0x61a5a9ebb6236e75L},
      {0xd1a79ec4L, 0x947cac1890c76e47L, 0xcfab28bd9e862dcfL},
      {0xc5bb72d3L, 0xa1b5ede111043300L, 0x869dec214e209e3eL},
    },
    {
      {0xce094b13L, 0x2898166aa9119a49L, 0xd05ec33fe275acf5L},
      {0xd945ae2eL, 0xab36907675664c87L, 0x22757b39349eab4cL},
      {0xf68b13c9L, 0x177f0d2eb60d7340L, 0xcc5d5c753755436bL},
    },
    {
      {0x2785e57aL, 0xa079bcb4e9b3c169L, 0x81fb22b42878b06aL},
      {0x38e7de5fL, 0xd30adcfc217837c0L, 0xe53226a389fd2938L},
      {0xd074c03dL, 0x1a06c2170a911ebcL, 0xb8bba0c32e7be9d6L},
    },
    {
      {0x5b26ceb5L, 0xba0930eca5283272L, 0x5ccd505560cc584dL},
      {0x31a307abL, 0x469f5aa387900d83L, 0x57d4a651636bdd7eL},
      {0xdc83f500L, 0xc2aec37d5329d179L, 0x7a2ddc8e044edd09L},
    },
  };
}
