
#include <cstring>
#include <cstdio>
#include "MurmurHash3.h"

int main() {
  const char* msg = "Will it get some wind for the sailboat";
  const int len = strlen(msg);
  const uint32_t seeds[] = {0, 0x05E15AA0, 0xF5E15AA0};
  const uint32_t hash[4] = {};
  printf("package com.seismotech.hashish.impl.murmur3;\n"
         "\n/* Autogenerated class."
         "\n * See ideas/murmur/murmur3/generate-data.cpp"
         "\n */"
         "\nclass MurmurTestData {");
  
  printf("\n  static final int[] SEEDS = {");
  for (int i = 0; i < 3; i++) printf("0x%x,", seeds[i]);
  printf("};");

  printf("\n  static final String VERSE = \"%s\";"
         "\n  static final long[][][] EXPECTED = {", msg);
  for (int i = 0; i <= len; i++) {
    printf("\n    {");
    for (int j = 0; j < 3; j++) {
      MurmurHash3_x86_32(msg, i, seeds[j], (void*) &hash);
      printf("\n      {0x%xL", hash[0]);
      MurmurHash3_x86_128(msg, i, seeds[j], (void*) &hash);
      printf(", 0x%lxL",
             *(uint64_t *) hash ^ *((uint64_t *) hash + 1));
      MurmurHash3_x64_128(msg, i, seeds[j], (void*) &hash);
      printf(", 0x%lxL},",
             *(uint64_t *) hash ^ *((uint64_t *) hash + 1));
    }
    printf("\n    },");
  }
  printf("\n  };"
         "\n}"
         "\n");
  return 0;
}
