name: Project build
run-name: ${{github.actor}} is building ${{github.repository}} ${{github.ref}}
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup JDK 17 for x86
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          architecture: x64
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build
        run: ./gradlew build -x test
      - name: Publish
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{secrets.SEISMO_TOKEN}}
